import { Participant } from '../../components/datingLobby/BallonDatingLobby/Participants';

export const participantsData: Participant[] = [
  {
    id: '1',
    name: 'Sofia Martinez',
    age: 29,
    profileImage: require('../../assets/images/people/person1.png'),
    status: 'mic',
    hasNotification: true,
    hasInterests: true,
    isLiked: false,
    isDismissed: false,
  },
  {
    id: '2',
    name: 'John Johnson',
    age: 26,
    profileImage: require('../../assets/images/people/person2.png'),
    status: 'micOff',
    hasNotification: false,
    isLiked: false,
    isDismissed: false,
  },
  {
    id: '3',
    name: 'Michael Chen',
    age: 31,
    profileImage: require('../../assets/images/people/person3.png'),
    status: 'chat',
    hasNotification: true,
    isLiked: false,
    isDismissed: false,
  },
  {
    id: '4',
    name: 'Alex Rivera',
    age: 28,
    profileImage: require('../../assets/images/people/person4.png'),
    status: 'micOff',
    hasNotification: false,
    isLiked: false,
    isDismissed: true,
  },
  {
    id: '5',
    name: 'David Kim',
    age: 27,
    profileImage: require('../../assets/images/people/person5.png'),
    status: 'micOff',
    hasNotification: false,
    isLiked: true,
    isDismissed: false,
  },
  {
    id: '6',
    name: 'Lia Wong',
    age: 25,
    profileImage: require('../../assets/images/people/person6.png'),
    status: 'micOff',
    hasNotification: false,
    isLiked: true,
    isDismissed: false,
  },
];
